name: CI/CD for Dockerized Flask App


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  #The jobs will be executed in the written sequence
  #here build-test is for unit testing
  build-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest
      
      - name: run tests
        run: |
            pytest
      
  build-publish:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: ./DockerFile
        tags: ${{secrets.DOCKER_USERNAME}}/dockercicd:latest

    - name: Image digest
      run: echo ${{steps.build-publish.outputs.digest}}
